packages:
  - apps/*
  - packages/*

catalog:
  '@effect/platform-node': 4.0.0-beta.78
  '@effect/platform-node-shared': 4.0.0-beta.78
  '@effect/sql-sqlite-node': 4.0.0-beta.78
  '@types/node': 24.12.4
  effect: 4.0.0-beta.78
  typescript: ~6.0.3
  vitest: ^4.0.0

onlyBuiltDependencies:
  - electron
  - esbuild
  - better-sqlite3

overrides:
  '@effect/platform-node': 'catalog:'
  '@effect/platform-node-shared': 'catalog:'
  '@types/node': 'catalog:'
  effect: 'catalog:'
